# Generated by Django 3.1.2 on 2020-10-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamba',
            name='pic_url',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
