# Generated by Django 3.1.2 on 2020-10-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20201014_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamba',
            name='electricit',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
