# Generated by Django 3.1.2 on 2020-10-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20201014_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shamba',
            name='owner',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shamba',
            name='soil_type',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shamba',
            name='water',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
