# Generated by Django 3.1.2 on 2020-10-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20201014_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiambudivision',
            name='nl_name_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='varname_3',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
