# Generated by Django 3.1.2 on 2020-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20201014_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiambudivision',
            name='engtype_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='hasc_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='remarks_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='type_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='validfr_3',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambudivision',
            name='validto_3',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
