# Generated by Django 3.1.2 on 2020-10-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20201014_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiambulocation',
            name='engtype_4',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambulocation',
            name='remarks_4',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambulocation',
            name='type_4',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambulocation',
            name='validfr_4',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambulocation',
            name='validto_4',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='kiambulocation',
            name='varname_4',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
